### ISSUE TITLE
Error when trying upgradeable contracts

### ISSUE THREAD

**Issue by tab00** [axelarnetwork/axelar-cgp-solidity#126]
Is there any plan to create upgradeable versions of Axelar contracts?

I'm creating an upgradeable token contract and want it to be Axelar-enabled, so e.g. would inherit `IAxelarExecutable`. All inherited contracts that have a constructor need to be modified to an upgradeable version (e.g. change constructor to initializer).

It would then allow us to upgrade the token contract in future in case we ever need or want to (e.g. if vulnerabilities are found), whilst maintaining the publicly known address of the token, so upgrades would be seamless to token holders.

See: https://docs.openzeppelin.com/learn/upgrading-smart-contracts

**Comment by re1ro** [comment]
@tab00 you can find them here https://github.com/axelarnetwork/axelar-utils-solidity

**Comment by re1ro** [comment]
@tab00 both OpenZeppelin UUPS and our implementation are following the same [EIP-1967](https://eips.ethereum.org/EIPS/eip-1967) standard. The key difference is we are using the deterministic storage slots to avoid the problem of storage slots collision described here
https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#modifying-your-contracts 

In UUPS case you can just do 
```
import "@axelar-network/axelar-utils-solidity/contracts/interfaces/IAxelarGateway.sol"
import "@axelar-network/axelar-utils-solidity/contracts/executables/AxelarExecutable.sol"
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";

contract YourContract is Initializable, AxelarExecutable {
    // UUPS things
    
    // Token logic
    
    function gateway() public view override returns (IAxelarGateway gateway_) {
        gateway_ = gateway_from_storage;
    };

    function _execute(
        string memory sourceChain,
        string memory sourceAddress,
        bytes calldata payload
    ) internal override {
      // burn
    }

    function _executeWithToken(
        string memory sourceChain,
        string memory sourceAddress,
        bytes calldata payload,
        string memory tokenSymbol,
        uint256 amount
    ) internal override {}
}
```

**Comment by tab00** [comment]
Thanks @re1ro for the sample code.

Should the contract inherit `UUPSUpgradeable` as is done in OpenZeppelin's examples, in order for it to be compliant with UUPS ([eip-1822](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1822.md))?

Also, I notice that your code imports from `axelar-utils-solidity` whereas [ERC20CrossChain.sol](https://github.com/axelarnetwork/axelar-local-gmp-examples/blob/main/examples/cross-chain-token/ERC20CrossChain.sol), which I've been trying to follow, imports from `axelar-cgp-solidity`:
```solidity
import { IAxelarGateway } from '@axelar-network/axelar-cgp-solidity/contracts/interfaces/IAxelarGateway.sol';
import { IAxelarExecutable } from '@axelar-network/axelar-cgp-solidity/contracts/interfaces/IAxelarExecutable.sol';
```
Which example should we follow?

**Comment by re1ro** [comment]
@tab00  You are right, use `UUPSUpgradeable`.
We are moving the Executables into `axelar-utils-solidity` and that version is friendlier with Upgradable contracts. 
I guess it would be more correct to import `IAxelarGateway` from `axelar-cgp-solidity` 😄

**Comment by tab00** [comment]
I've made a fork of axelar-local-gmp-examples containing a branch with my attempt to use UUPS upgradeable contracts:
https://github.com/tab00/axelar-local-gmp-examples/tree/experiment-upgradeable

Changes are minimal, with the main ones being:
Setting a constant private key instead of random
Adding scripts/deployUpgradeable.js that uses OpenZeppelin's `deployProxy`.
Added an additional argument to `node scripts/test examples/cross-chain-token local` for address of upgradeable token contract that was deployed

To run the non-upgradeable version:
```
node scripts/createLocal

node scripts/deploy examples/cross-chain-token local
node scripts/test examples/cross-chain-token local "Ethereum" "Fantom" 1
```
To run the upgardeable contracts test:

```
delete .openzeppelin directory if it exists

node scripts/createLocal

npx hardhat run --network moonbeam scripts/deployUpgradeable.js
npx hardhat run --network avalanche scripts/deployUpgradeable.js
npx hardhat run --network fantom scripts/deployUpgradeable.js
npx hardhat run --network ethereum scripts/deployUpgradeable.js
npx hardhat run --network polygon scripts/deployUpgradeable.js

node scripts/test examples/cross-chain-token local "Ethereum" "Fantom" 1 [token contract address]
```

The non-upgradeable version works successfully as before with output:
```
--- Initially ---
Balance at Ethereum is 0
Balance at Fantom is 0
--- After getting some token on the source chain ---
Balance at Ethereum is 1
Balance at Fantom is 0
--- After ---
Balance at Ethereum is 0
Balance at Fantom is 1
```

My upgradeable contracts version fails before the transfer is made:
```
--- Initially ---
Balance at Ethereum is 0
Balance at Fantom is 0
--- After getting some token on the source chain ---
Balance at Ethereum is 1
Balance at Fantom is 0
C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\logger\lib\index.js:233
        var error = new Error(message);
                    ^

<ref *1> Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"id\":66,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"VM Exception while processing transaction: revert\",\"stack\":\"RuntimeError: VM Exception while processing transaction: revert\\n    at exactimate (C:\\\\Users\\\\-\\\\Documents\\\\Projects\\\\axelar-local-gmp-examples\\\\node_modules\\\\ganache\\\\dist\\\\node\\\\1.js:2:113332)\",\"code\":-32000,\"name\":\"RuntimeError\",\"data\":{\"hash\":null,\"programCounter\":186,\"result\":\"0x\",\"reason\":null,\"message\":\"revert\"}}}","error":{"code":-32000,"data":{"hash":null,"programCounter":186,"result":"0x","reason":null,"message":"revert"}},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x6ba6c57e\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"value\":\"0x493e0\",\"from\":\"0x3e0c282ad53ceddcebf4baa1064b8fa6d1620886\",\"to\":\"0x60b5810bf62c08a20785221fff1df721b6d28dd0\",\"data\":\"0x55d55dc100000000000000000000000000000000000000000000000000000000000000600000000000000000000000003e0c282ad53ceddcebf4baa1064b8fa6d16208860000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000646616e746f6d0000000000000000000000000000000000000000000000000000\"}],\"id\":66,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8500/3"}, tx={"data":"0x55d55dc100000000000000000000000000000000000000000000000000000000000000600000000000000000000000003e0c282ad53ceddcebf4baa1064b8fa6d16208860000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000646616e746f6d0000000000000000000000000000000000000000000000000000","to":{},"from":"0x3E0C282ad53ceddCEbF4BAa1064b8FA6D1620886","value":{"type":"BigNumber","hex":"0x0493e0"},"type":2,"maxFeePerGas":{"type":"BigNumber","hex":"0x6ba6c57e"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.6.2)
    at Logger.makeError (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\logger\lib\index.js:233:21)
    at Logger.throwError (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\logger\lib\index.js:242:20)
    at C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\abstract-signer\lib\index.js:365:47
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 8) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: Error: processing response error (body="{\"id\":66,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"VM Exception while processing transaction: revert\",\"stack\":\"RuntimeError: VM Exception while processing transaction: revert\\n    at exactimate (C:\\\\Users\\\\-\\\\Documents\\\\Projects\\\\axelar-local-gmp-examples\\\\node_modules\\\\ganache\\\\dist\\\\node\\\\1.js:2:113332)\",\"code\":-32000,\"name\":\"RuntimeError\",\"data\":{\"hash\":null,\"programCounter\":186,\"result\":\"0x\",\"reason\":null,\"message\":\"revert\"}}}", error={"code":-32000,"data":{"hash":null,"programCounter":186,"result":"0x","reason":null,"message":"revert"}}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x6ba6c57e\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"value\":\"0x493e0\",\"from\":\"0x3e0c282ad53ceddcebf4baa1064b8fa6d1620886\",\"to\":\"0x60b5810bf62c08a20785221fff1df721b6d28dd0\",\"data\":\"0x55d55dc100000000000000000000000000000000000000000000000000000000000000600000000000000000000000003e0c282ad53ceddcebf4baa1064b8fa6d16208860000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000646616e746f6d0000000000000000000000000000000000000000000000000000\"}],\"id\":66,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:8500/3", code=SERVER_ERROR, version=web/5.6.1)
      at Logger.makeError (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\logger\lib\index.js:233:21)
      at Logger.throwError (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\logger\lib\index.js:242:20)
      at C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\web\lib\index.js:305:32
      at step (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\web\lib\index.js:33:23)
      at Object.next (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\web\lib\index.js:14:53)
      at fulfilled (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\web\lib\index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"id":66,"jsonrpc":"2.0","error":{"message":"VM Exception while processing transaction: revert","stack":"RuntimeError: VM Exception while processing transaction: revert\\n    at exactimate (C:\\\\Users\\\\-\\\\Documents\\\\Projects\\\\axelar-local-gmp-examples\\\\node_modules\\\\ganache\\\\dist\\\\node\\\\1.js:2:113332)","code":-32000,"name":"RuntimeError","data":{"hash":null,"programCounter":186,"result":"0x","reason":null,"message":"revert"}}}',
    error: Error: VM Exception while processing transaction: revert
        at getResult (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:191:21)
        at processJsonFunc (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\web\lib\index.js:348:22)
        at C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\web\lib\index.js:280:46
        at step (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\web\lib\index.js:33:23)
        at Object.next (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\web\lib\index.js:14:53)
        at fulfilled (C:\Users\-\Documents\Projects\axelar-local-gmp-examples\node_modules\@ethersproject\web\lib\index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      code: -32000,
      data: {
        hash: null,
        programCounter: 186,
        result: '0x',
        reason: null,
        message: 'revert'
      }
    },
    requestBody: '{"method":"eth_estimateGas","params":[{"type":"0x2","maxFeePerGas":"0x6ba6c57e","maxPriorityFeePerGas":"0x59682f00","value":"0x493e0","from":"0x3e0c282ad53ceddcebf4baa1064b8fa6d1620886","to":"0x60b5810bf62c08a20785221fff1df721b6d28dd0","data":"0x55d55dc100000000000000000000000000000000000000000000000000000000000000600000000000000000000000003e0c282ad53ceddcebf4baa1064b8fa6d16208860000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000646616e746f6d0000000000000000000000000000000000000000000000000000"}],"id":66,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'http://localhost:8500/3'
  },
  tx: {
    data: '0x55d55dc100000000000000000000000000000000000000000000000000000000000000600000000000000000000000003e0c282ad53ceddcebf4baa1064b8fa6d16208860000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000646616e746f6d0000000000000000000000000000000000000000000000000000',
    to: Promise { '0x60B5810bf62c08A20785221FfF1DF721b6D28dd0' },
    from: '0x3E0C282ad53ceddCEbF4BAa1064b8FA6D1620886',
    value: BigNumber { _hex: '0x0493e0', _isBigNumber: true },
    type: 2,
    maxFeePerGas: BigNumber { _hex: '0x6ba6c57e', _isBigNumber: true },
    maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
    nonce: Promise { 3 },
    gasLimit: Promise { <rejected> [Circular *1] },
    chainId: Promise { 2503 }
  }
}
```

What could be the problem?

**Comment by re1ro** [comment]
@Foivos could you please take a look and see where is the issue?

**Comment by tab00** [comment]
How's progress, guys? What does `result: '0x'` mean?

**Comment by tab00** [comment]
> @Foivos could you please take a look and see where is the issue?

Is @Foivos looking into the problem?
